
target 'BANBANSEARCH' do
  pod 'AFNetworking'
  pod 'Masonry'
  pod 'ReactiveObjC'
  pod 'GoogleMaps', '~> 9.4.0'
#  pod 'GoogleMapDirection', '~> 1.2.1'
#  pod 'GooglePlaces'
#  pod 'GooglePlacePicker'
  #pod 'MJRefresh'
  pod 'BRPickerView'

#  pod 'GKImagePicker', '~> 0.0.1'
  pod 'MJExtension'
  pod 'SDWebImage'
  pod 'MBProgressHUD'
  pod 'ZYQAssetPickerController', '~> 1.3.1'
  pod 'TZImagePickerController'
  pod 'IQKeyboardManager'
  pod 'JZLocationConverter'
end
